# Generated by Django 3.1.2 on 2020-10-11 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201011_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 12, 28, 0, 226843, tzinfo=utc), verbose_name='Date'),
        ),
    ]
