# Generated by Django 3.1.2 on 2020-10-13 06:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20201011_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 6, 56, 41, 96891, tzinfo=utc), verbose_name='Date'),
        ),
    ]
