# Generated by Django 3.1.2 on 2020-10-13 07:08

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20201012_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cnic',
            field=models.CharField(default='', max_length=13, validators=[django.core.validators.RegexValidator(message="CNIC must be entered in the format: 'xxxxxxxxxxxxx'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 7, 8, 21, 298733, tzinfo=utc), verbose_name='Date'),
        ),
    ]
