# Generated by Django 3.1.2 on 2020-10-13 07:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20201013_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ppic',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 7, 14, 6, 313890, tzinfo=utc), verbose_name='Date'),
        ),
    ]
