# Generated by Django 3.1.2 on 2020-10-13 10:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20201013_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 10, 29, 2, 513201, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=14),
        ),
    ]
