# Generated by Django 3.1.2 on 2020-10-13 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20201013_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 10, 13, 11, 3, 6, 813668, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=14),
        ),
    ]
