# Generated by Django 3.1.2 on 2020-12-23 10:26

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20201223_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='doj',
            field=models.DateField(default=datetime.datetime(2020, 12, 23, 10, 26, 25, 924761, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='', max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Format: '03XXxxxxxxx'  Enter 11 Digits.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
